language: php

dist: trusty

services:
  - rabbitmq

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

env:
  - IS_MLE86_WQ_AMQP_TEST=1

before_install:
  - composer self-update

install:
  - composer install

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/php-coveralls

